from typing import Tuple, Dict, Any
!pip install -r ../../../requirements.txt

In [1]:
import os
import sys

parent_dir = os.path.abspath('..')
sys.path.insert(0, parent_dir)

In [2]:
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

In [3]:
import pandas as pd
pd.options.mode.chained_assignment = None  # Disable the warning

import pickle
import numpy as np
import kagglehub

from library.rating import get_explicit_rating, get_implicit_rating_out_of_positive_ratings, split_matrix
from library.svdpp import SVDpp

INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.


# Feature selection

The only dataset that is necessary for our purposes is **review** dataset since:
- it contains the information about explicit ratings (the mean of the field **stars** for pairs of users and items, check the chapter **Feature engineering** for more details)
- it contains the information for implicit rating (check the chapter **Feature engineering** for more details)
- it already contains only those users who provided at least one review and those items that received at least one estimation

There are two paths of working with the dataset that contains more than **900 000** rows

*The standard flow:*
1. Download dataset from Kaggle
2. Drop the reviews for closed businesses (`is_open == True`)
3. Drop the reviews were provided by users that assessed less than **threshold** items (check the threshold definition in `/eda/yelp.ipynb`) 
4. Use all the dataset in the purpose of analysis, training and testing

*The "sampled" flow* (provided in `/eda/yelp.ipynb`):
1. Download dataset from Kaggle
2. Drop the reviews for closed businesses (`is_open == True`)
3. Drop the reviews were provided by users that assessed less than **threshold** items (check the threshold definition in `/eda/yelp.ipynb`) 
4. Sample **10%** randomly
5. Check similarity of mathematical moments (`.describe()`) and dataset balancing (`.value_counts()`) with main dataset (initial YELP)

In the purpose of time-efficiency and due to the lack of power **the "sampled" flow** was chosen during EDA, and the sampled dataset was saved using the following path **`/eda/dataset_samples`**

In [4]:
PATH = '../../../eda/dataset_samples/sampled_yelp.csv'

Reviews' features:
- `review_id` | `user_id` | `business_id` - id of the review and foreign keys (one user can leave several reviews for one item)
- `stars` - **explicit rating** provided by user for the particular item in the particular moment
- `useful` | `funny` | `cool`  - user's flags about (presumably) review. We don't drop this feature since it's necessary to get any evidences that theory about the nature of the feature is right - check the **opportunity of usage them for implicit rating** 
- `text` - the content of review (can be useful for potential sentimental analysis)
- `date` - the timestamp of review

In [5]:
review_df = pd.read_csv(PATH)
review_df

review_id                 user_id  \
0       J5Q1gH4ACCj6CtQG7Yom7g  56gL9KEJNHiSDUoyjk2o3Q   
1       HlXP79ecTquSVXmjM10QxQ  bAt9OUFX9ZRgGLCXG22UmA   
2       JBBULrjyGx6vHto2osk_CQ  NRHPcLq2vGWqgqwVugSgnQ   
3       U9-43s8YUl6GWBFCpxUGEw  PAxc0qpqt5c2kA0rjDFFAg   
4       8T8EGa_4Cj12M6w8vRgUsQ  BqPR1Dp5Rb_QYs9_fz9RiA   
...                        ...                     ...   
699023  35n-AfizcW5N5KoKkYBSiQ  0PIrTmRx2EXHjAJOxxWvLA   
699024  b8_VWg1UF-Xwbg2PBiYDuA  X3fYkqlfQFNI3vP2sS-JWw   
699025  ZRNDyqZMoBvfDn1WeKzI3w  ZEcFnCWWT7wGEbPZkPQb0Q   
699026  7-uxIDn4CkcBJedNm6IdTw  nWMwtH1xGvn1Utm11Ufxow   
699027  lLE0oQumH1yqPH9YpYdmTA  T56vEU0r6Sk9W6vip5FhPA   

                   business_id  stars  useful  funny  cool  \
0       8yR12PNSMo6FBYx1u5KPlw      2       1      0     0   
1       pBNucviUkNsiqhJv5IFpjg      5       0      0     0   
2       8sf9kv6O4GgEb0j1o22N1g      5       0      0     0   
3       XwepyB7KjJ-XGJf0vKc6Vg      4       0      0     0   
4       prm5wvpp0OHJBlrvTj9uOg      5       0      0     0   
...                        ...    ...     ...    ...   ...   
699023  IM0gPEyNRUoZVmYZhwuBpQ      5       0      0     0   
699024  l_slvEnh4v3W8BXF1gYlcQ      5       0      0     0   
699025  Mr7Aov2n7wPCpwaUxk8lCw      4       0      0     0   
699026  v9jNsSprsNpERYvyTOAzqw      5       2      1     1   
699027  b4dvH9VUIY5mwUr1Y-M1eQ      5       0      0     0   

                                                     text                 date  
0       Went for lunch and found that my burger was me...  2018-04-04 21:09:53  
1       I needed a new tires for my wife's car. They h...  2020-05-24 12:22:14  
2       Jim Woltman who works at Goleta Honda is 5 sta...  2019-02-14 03:47:48  
3       Been here a few times to get some shrimp.  The...  2013-04-27 01:55:49  
4       This is one fantastic place to eat whether you...  2019-05-15 18:29:25  
...                                                   ...                  ...  
699023  Today was our first time to go here and the st...  2019-04-15 22:55:39  
699024  Sharkeez still the best place on State Street ...  2016-01-08 01:11:29  
699025  Good vegetarian selections. Excellent sangria....  2013-05-13 12:23:06  
699026  Normally I wouldn't review a buffet but I feel...  2019-05-27 18:29:40  
699027  Eagle Automotive is a fantastic repair shop ru...  2017-08-03 19:15:01  

[699028 rows x 9 columns]

Reasons of feature dropping:
- since `useful | funny | cool` features describe the preferences of other users about this particular review, not an item, they can't be used for calculations of **explicit** and **implicit** ratings (our assumption is that these features are reactions that user can give to review that theoretically describes the user-to-user relations) 
- `review_id` won't be dropped, but will be used for indexing since it's unique field
- `text` of review won't be used for implicit or explicit ratings so this feature can be also dropped 

In [6]:
REMAINED_FEATURES = ['review_id', 'user_id', 'business_id', 'stars', 'date']

filtered_review_df = review_df[REMAINED_FEATURES]
filtered_review_df.set_index('review_id', inplace=True)
filtered_review_df

user_id             business_id  stars  \
review_id                                                                       
J5Q1gH4ACCj6CtQG7Yom7g  56gL9KEJNHiSDUoyjk2o3Q  8yR12PNSMo6FBYx1u5KPlw      2   
HlXP79ecTquSVXmjM10QxQ  bAt9OUFX9ZRgGLCXG22UmA  pBNucviUkNsiqhJv5IFpjg      5   
JBBULrjyGx6vHto2osk_CQ  NRHPcLq2vGWqgqwVugSgnQ  8sf9kv6O4GgEb0j1o22N1g      5   
U9-43s8YUl6GWBFCpxUGEw  PAxc0qpqt5c2kA0rjDFFAg  XwepyB7KjJ-XGJf0vKc6Vg      4   
8T8EGa_4Cj12M6w8vRgUsQ  BqPR1Dp5Rb_QYs9_fz9RiA  prm5wvpp0OHJBlrvTj9uOg      5   
...                                        ...                     ...    ...   
35n-AfizcW5N5KoKkYBSiQ  0PIrTmRx2EXHjAJOxxWvLA  IM0gPEyNRUoZVmYZhwuBpQ      5   
b8_VWg1UF-Xwbg2PBiYDuA  X3fYkqlfQFNI3vP2sS-JWw  l_slvEnh4v3W8BXF1gYlcQ      5   
ZRNDyqZMoBvfDn1WeKzI3w  ZEcFnCWWT7wGEbPZkPQb0Q  Mr7Aov2n7wPCpwaUxk8lCw      4   
7-uxIDn4CkcBJedNm6IdTw  nWMwtH1xGvn1Utm11Ufxow  v9jNsSprsNpERYvyTOAzqw      5   
lLE0oQumH1yqPH9YpYdmTA  T56vEU0r6Sk9W6vip5FhPA  b4dvH9VUIY5mwUr1Y-M1eQ      5   

                                       date  
review_id                                    
J5Q1gH4ACCj6CtQG7Yom7g  2018-04-04 21:09:53  
HlXP79ecTquSVXmjM10QxQ  2020-05-24 12:22:14  
JBBULrjyGx6vHto2osk_CQ  2019-02-14 03:47:48  
U9-43s8YUl6GWBFCpxUGEw  2013-04-27 01:55:49  
8T8EGa_4Cj12M6w8vRgUsQ  2019-05-15 18:29:25  
...                                     ...  
35n-AfizcW5N5KoKkYBSiQ  2019-04-15 22:55:39  
b8_VWg1UF-Xwbg2PBiYDuA  2016-01-08 01:11:29  
ZRNDyqZMoBvfDn1WeKzI3w  2013-05-13 12:23:06  
7-uxIDn4CkcBJedNm6IdTw  2019-05-27 18:29:40  
lLE0oQumH1yqPH9YpYdmTA  2017-08-03 19:15:01  

[699028 rows x 4 columns]

# Rating extracting

Below predefined constants for this section

In [7]:
# The threshold for implicit ratings calculations (only positive ratings are considered and explicit ratings are from 1 to 5)
IMPLICIT_THRESHOLD = 4

In [8]:
filtered_review_df["date"] = pd.to_datetime(filtered_review_df["date"]).astype(np.int64) // 10**9 
filtered_review_df

user_id             business_id  stars  \
review_id                                                                       
J5Q1gH4ACCj6CtQG7Yom7g  56gL9KEJNHiSDUoyjk2o3Q  8yR12PNSMo6FBYx1u5KPlw      2   
HlXP79ecTquSVXmjM10QxQ  bAt9OUFX9ZRgGLCXG22UmA  pBNucviUkNsiqhJv5IFpjg      5   
JBBULrjyGx6vHto2osk_CQ  NRHPcLq2vGWqgqwVugSgnQ  8sf9kv6O4GgEb0j1o22N1g      5   
U9-43s8YUl6GWBFCpxUGEw  PAxc0qpqt5c2kA0rjDFFAg  XwepyB7KjJ-XGJf0vKc6Vg      4   
8T8EGa_4Cj12M6w8vRgUsQ  BqPR1Dp5Rb_QYs9_fz9RiA  prm5wvpp0OHJBlrvTj9uOg      5   
...                                        ...                     ...    ...   
35n-AfizcW5N5KoKkYBSiQ  0PIrTmRx2EXHjAJOxxWvLA  IM0gPEyNRUoZVmYZhwuBpQ      5   
b8_VWg1UF-Xwbg2PBiYDuA  X3fYkqlfQFNI3vP2sS-JWw  l_slvEnh4v3W8BXF1gYlcQ      5   
ZRNDyqZMoBvfDn1WeKzI3w  ZEcFnCWWT7wGEbPZkPQb0Q  Mr7Aov2n7wPCpwaUxk8lCw      4   
7-uxIDn4CkcBJedNm6IdTw  nWMwtH1xGvn1Utm11Ufxow  v9jNsSprsNpERYvyTOAzqw      5   
lLE0oQumH1yqPH9YpYdmTA  T56vEU0r6Sk9W6vip5FhPA  b4dvH9VUIY5mwUr1Y-M1eQ      5   

                              date  
review_id                           
J5Q1gH4ACCj6CtQG7Yom7g  1522876193  
HlXP79ecTquSVXmjM10QxQ  1590322934  
JBBULrjyGx6vHto2osk_CQ  1550116068  
U9-43s8YUl6GWBFCpxUGEw  1367027749  
8T8EGa_4Cj12M6w8vRgUsQ  1557944965  
...                            ...  
35n-AfizcW5N5KoKkYBSiQ  1555368939  
b8_VWg1UF-Xwbg2PBiYDuA  1452215489  
ZRNDyqZMoBvfDn1WeKzI3w  1368447786  
7-uxIDn4CkcBJedNm6IdTw  1558981780  
lLE0oQumH1yqPH9YpYdmTA  1501787701  

[699028 rows x 4 columns]

## Explicit rating 

In [9]:
explicit_ratings, last_dates, user_mapping, item_mapping = get_explicit_rating(filtered_review_df, "user_id", "business_id", "stars", "date")

explicit_ratings.toarray() , last_dates.toarray() 

(array([[2., 0., 0., ..., 0., 0., 0.],
        [0., 5., 0., ..., 0., 0., 0.],
        [0., 0., 5., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[1522876193,          0,          0, ...,          0,          0,
                  0],
        [         0, 1590322934,          0, ...,          0,          0,
                  0],
        [         0,          0, 1550116068, ...,          0,          0,
                  0],
        ...,
        [         0,          0,          0, ...,          0,          0,
                  0],
        [         0,          0,          0, ...,          0,          0,
                  0],
        [         0,          0,          0, ...,          0,          0,
                  0]]))

## Implicit rating

# Train / validation / test split

In [10]:
DIVISIONS = [0.7, 0.2, 0.1]

train_matrix, validation_matrix, test_matrix = split_matrix(explicit_ratings, last_dates, DIVISIONS)
train_matrix.toarray(), validation_matrix.toarray(), test_matrix.toarray()

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [11]:
train_df = pd.DataFrame.sparse.from_spmatrix(train_matrix)
implicit_ratings = get_implicit_rating_out_of_positive_ratings(train_df, "user_id", "business_id", "stars", IMPLICIT_THRESHOLD)
implicit_ratings

KeyError: 'stars'

# Hyperparameters tuning

In [ ]:
svd_pp = SVDpp()
svd_pp.fit(ratings=train_matrix, implicit_rating=implicit_ratings, user_mapping=user_mapping, item_mapping=item_mapping)


In [12]:
svd_pp.predict(user_id="F9vYcUknd9JY2lxsaEObQQ", item_id="T6ihfy4SYiF4PvuE6Y0VPA")

4.5

# Model testing

# Model saving 

The following code saves the result object to reuse **the trained model** in the service

In [13]:
with open("./models/svd_pp.pkl", "wb") as f:
    pickle.dump(svd_pp, f)